### ISSUE TITLE
Can't run on Windows

### ISSUE THREAD

**Issue by Firedrake969** [jayforsythe/scrabble#1]
```
Traceback (most recent call last):
  File "C:\Users\me\Documents\GitHub\scrabble\__main__.py", line 3, in <module>
    import blessed
  File "C:\Python27\lib\site-packages\blessed\__init__.py", line 12, in <module>
    from terminal import Terminal
  File "C:\Python27\lib\site-packages\blessed\terminal.py", line 7, in <module>
    import termios
ImportError: No module named termios
```

**Comment by jayforsythe** [comment]
It seems to be a problem with the library itself. I'll check later if there's anything on the gh.

**Comment by jayforsythe** [comment]
I'm rewriting the code to work better and be less messy, so I'm gonna close this.

**Comment by Firedrake969** [comment]
So my issue triggered a complete refactor?  :package:
